name: CI for Tenx Insurance Project

on:
  push:
    branches: [ main, task-1, task-2, task-3, task-4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter  # For nbconvert
        pip install flake8   # Optional: Linter
        pip install dvc[gdrive]  # If you're using DVC

    - name: Pull Data with DVC (Optional)
      run: |
        dvc pull || echo "Skipping dvc pull if no remote is configured"

    - name: Run Task 1 Notebook (Optional)
      run: |
        jupyter nbconvert --to notebook --execute --allow-errors notebooks/task-1-eda.ipynb --output executed-task-1.ipynb